version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    container_name: fastapi_project
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo_data:
